// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCta5U-MRtRgJjyn1x_zFYrJIz73QZz110',
    appId: '1:482872503776:web:3b5e551456192f848dcf85',
    messagingSenderId: '482872503776',
    projectId: 'tiktok-b9083',
    authDomain: 'tiktok-b9083.firebaseapp.com',
    storageBucket: 'tiktok-b9083.firebasestorage.app',
    measurementId: 'G-ZV0ETDWPZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPB0E4TNcjW8Cvs7BzBZCNx87qSQCLwXI',
    appId: '1:482872503776:android:a2858109c488a59d8dcf85',
    messagingSenderId: '482872503776',
    projectId: 'tiktok-b9083',
    storageBucket: 'tiktok-b9083.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi93ZJo5B8ibV69ZY4FhSBWYnDuxS2Jv8',
    appId: '1:482872503776:ios:30dc8937fa7d34358dcf85',
    messagingSenderId: '482872503776',
    projectId: 'tiktok-b9083',
    storageBucket: 'tiktok-b9083.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi93ZJo5B8ibV69ZY4FhSBWYnDuxS2Jv8',
    appId: '1:482872503776:ios:30dc8937fa7d34358dcf85',
    messagingSenderId: '482872503776',
    projectId: 'tiktok-b9083',
    storageBucket: 'tiktok-b9083.firebasestorage.app',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCta5U-MRtRgJjyn1x_zFYrJIz73QZz110',
    appId: '1:482872503776:web:5a1b7e69ff70d6938dcf85',
    messagingSenderId: '482872503776',
    projectId: 'tiktok-b9083',
    authDomain: 'tiktok-b9083.firebaseapp.com',
    storageBucket: 'tiktok-b9083.firebasestorage.app',
    measurementId: 'G-DXPCZBZCEV',
  );

}